name: Atomic Bisecter
on:
 workflow_dispatch:
   inputs:
    good:
      description: 'The commit that is known to be good'
      required: true
    bad:
      description: 'The commit that is known to be bad'
      required: true
      default: 'master'
permissions:
  contents: read

jobs:
  bisect:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout ui-kit
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: coveo/ui-kit
          path: ui-kit
          fetch-depth: 0
      - name: Checkout bisecter
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: bisecter
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
      - name: Init Bisecter
        run: npm ci
        working-directory: bisecter
      - name: Bisect
        run: |
          git bisect start ${{ github.event.inputs.bad }} ${{ github.event.inputs.good }}
          git bisect run node ../bisecter/packages/atomic-bisecter/index.js
        working-directory: ui-kit
      - name: Summary
        run: |
          echo "Bisect complete ðŸ›" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          git bisect view >> $GITHUB_STEP_SUMMARY
        working-directory: ui-kit